### ISSUE TITLE
"Veto loop" possible

### ISSUE THREAD

**Issue by JulianLindner** [ShrimpCryptid/Secret-Hitler-Online#10]
When the Chancelor chooses to do a veto, the president can decide. If the president says no, the same screen goes back to the chancelor.
The chancelor should then not have the possibility to do veto again. Otherwise it is possible, that they get caught in a loop.
He/she should instead be only able to chose the policies.

The original rules say, that the veto failed when one of them is against it.

**Comment by ShrimpCryptid** [comment]
This was something I originally left in, figuring that players would avoid getting stuck in a repeated loop. You're right though, according to the original game rules, the veto can't happen more than once per president.

**Comment by ShrimpCryptid** [comment]
Late fix, but this change has been made! The veto option no longer appears if a veto has already been made that turn.

**Comment by Hacime** [comment]
When we played the last time, the Veto Loop was still active. when the president didn't agree, it went back to the chancelor again.

**Comment by ShrimpCryptid** [comment]
Hi, Hacime. Are you saying that the Chancellor had the veto option still available again, or just that the Chancellor had to choose the policy?

**Comment by Hacime** [comment]
Oh, my fault. it went back to the chancelor to choose the policy it seems. I was not the chancelor but when it went back, I thought it's the loop, sorry.
however, does it have to go back to the chancelor to choose the policy? normally it's 2 reds when the chancelor will use his veto or 2 blues for a fascist chancellor. theoretically, once the president doesn't agree, the available policy could be enacted automatically. but maybe not necessary to change as it works currently, too.

**Comment by ShrimpCryptid** [comment]
Thank you for the feedback. This mechanic (forcing the Chancellor to enact a policy after a failed veto) is directly derived from the original board mechanics. I think removing that step would make the actions occurring less clear. If you want to continue this discussion, please move it to a new Issue thread.
