### ISSUE TITLE
Image icons render black

### ISSUE THREAD

**Issue by ShrimpCryptid** [ShrimpCryptid/Secret-Hitler-Online#11]
Parts of the player icons appear black in Chrome browsers.

**Comment by AdmiralAnne** [comment]
Yes ~ It happens in every game. The screen goes black for 1 or more players.

**Comment by ShrimpCryptid** [comment]
@AdmiralAnne this sounds like it might be a separate issue? Is it just parts of the player icons of the entire screen that's going black?

**Comment by AdmiralAnne** [comment]
> @AdmiralAnne this sounds like it might be a separate issue? Is it just parts of the player icons of the entire screen that's going black?

It's just parts of the screen. Like .. 60% length 30% width of the screen becomes black. And it blocks us from making any actions to continue the game. 

Sometimes it happens only for 1 player and sometimes everyone experiences the same issue all at the same.

**Comment by ShrimpCryptid** [comment]
Yeah, I'll make this into a second issue. When in the game does it happen?

**Comment by AdmiralAnne** [comment]
Haven't encountered it early game. Mostly mid game after like.. 10 mins. 

I was using Chrome and Firefox. Both showed the issue~

**Comment by ShrimpCryptid** [comment]
@AdmiralAnne I think your problem is linked to a different issue (https://github.com/ShrimpCryptid/Secret-Hitler-Online/issues/12) which I'm looking into.

I think the images turning black are due to a change in browser SVG standards. Going through the SVG files and changing any swatches to fill-only seems to fix the issue.
![image](https://user-images.githubusercontent.com/30200665/125152493-c3230080-e101-11eb-949a-426f1a3b57e8.png)
![image](https://user-images.githubusercontent.com/30200665/125152621-873c6b00-e102-11eb-8d00-7e0a585c81f2.png)

**Comment by ShrimpCryptid** [comment]
All player icons are fixed!
