### ISSUE TITLE
Killed player becomes president

### ISSUE THREAD

**Issue by Hacime** [ShrimpCryptid/Secret-Hitler-Online#14]
When the player on the right of the president gets killed, the very next turn the president token moves on to the killed player
and the game hangs and can't be continued anymore. Instead it should ignore the recently killed player and move to the following player who comes afterwards.
The game logic doesn't recognize that the player was just killed if it's the player on the right side of the president.

**Comment by ShrimpCryptid** [comment]
I was not able to recreate this issue when I tested it with a 5-player lobby. Can you give me some more information about when and where you're encountering this bug?

- What browser are you using?
- How many players do you usually play with?
- When was the last time this issue occurred?

If you could record a video next time it happens that would also be very helpful.

**Comment by Hacime** [comment]
It happened only once maybe 1 week ago.
I just tested it myself and it also didn't happen again.
Sorry, I also can't recreate it at the moment. Maybe this can be closed. Thanks.

**Comment by ShrimpCryptid** [comment]
I looked through the code for the server and it seems like it should be handling execution cases when the President role transitions. Feel free to reopen this issue if you start seeing it again!
