### ISSUE TITLE
Unable to use names with diacritics.

### ISSUE THREAD

**Issue by IamPhate** [ShrimpCryptid/Secret-Hitler-Online#15]
Joining game while using name that includes diacritics (characters such as š,ř,ž,á,í etc.) creates giberrish in the name. Furthermore, starting the game while having such a name makes you unable to join the game at all.

**Comment by ShrimpCryptid** [comment]
Thanks for letting me know, this issue should be fixed in the latest build! It looks like it was caused by incorrect decoding/encoding of player names when communicating with the server.
