### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by rob-3** [ShrimpCryptid/Secret-Hitler-Online#152]
Hi - first, thank you for building this application. I use it regularly with some friends and it's a blast every time!

I was wondering whether the lack of an open-source software license is simply an oversight or if full copyright rights are intentionally retained. I am interesting in investigating [some](https://github.com/ShrimpCryptid/Secret-Hitler-Online/issues/141) [bugs](https://github.com/ShrimpCryptid/Secret-Hitler-Online/issues/138) I run into, but without a license on the software, I'm not technically legally able to.

The excellent https://choosealicense.com/no-permission/ website from GitHub describes some of the issues with not having a license.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

If you're interested in adding a license, https://choosealicense.com/licenses/ offers some of the most common options.

* [The MIT License](https://choosealicense.com/licenses/mit/) is a "do-what-you-like" license.
* [AGPL](https://choosealicense.com/licenses/agpl-3.0/) requires changes to remain open source, which usually dissuades companies from trying to commercialize the project.

Please get confirmation from all previous committers to the project before applying any license.

**Comment by rob-3** [comment]
Ah - I just noticed this is under [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) as mentioned in the README. Closing the issue.

It might be worthwhile to add the license text to a LICENSE file so that GitHub can list the license information in the sidebar.

**Comment by ShrimpCryptid** [comment]
Thanks! I'll reopen this so this is added to my list of TODOs.

**Comment by ShrimpCryptid** [comment]
LICENSE file has been added. Thank you!
