### ISSUE TITLE
Servers down on secret-hitler.online

### ISSUE THREAD

**Issue by nothello0** [ShrimpCryptid/Secret-Hitler-Online#161]
Whe trynna play secret hitler in class and we cant connect to the server please fix

**Comment by ShrimpCryptid** [comment]
Hm, it looks like the servers are working now? Can you confirm whether you're still having connection issues?

**Comment by ShrimpCryptid** [comment]
![image](https://github.com/user-attachments/assets/7dd9de9f-b472-4b12-9542-96784da31790)

Adding a note, there was a spike in HTTP response time on the 17th, but it was confined to a relatively short duration.

**Comment by nothello0** [comment]
There is no longer a problem!
