### ISSUE TITLE
Presidential Powers active when vote is skipped

### ISSUE THREAD

**Issue by kapdjim** [ShrimpCryptid/Secret-Hitler-Online#18]
according to official rules, we cant use powers when vote is skiped

**Comment by ShrimpCryptid** [comment]
Thanks for opening an issue! This actually touches on a couple rules that I wasn't aware of.

For reference, this is the wording used by the rulebook:
> **Election tracker**: if the group rejects three governments in a row... immediately reveal the Policy on top of the policy deck and enact it. **Any power granted by this Policy is ignored, but the Election Tracker resets, and existing term-limits are forgotten.**

The changes that need to happen include:
- Resetting all term limits (remove last Chancellor and President on server)
- Skip to Post Presidential phase after a failed vote, and ignore the presidential power.

I will work on this for the next update!

**Comment by allredhayden** [comment]
Do you know when the next update will go live? I'm going to try this out in a few days with a large group of friends. So excited!

**Comment by ShrimpCryptid** [comment]
Thanks for the ping on this! The code change was pretty much complete but needed to be tested.

I've pushed the change and everything appears to be working smoothly. Let me know if any issues appear!
