### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by allredhayden** [ShrimpCryptid/Secret-Hitler-Online#19]
Sorry, I didn’t know where else to put this. Could I make a donation to your project? I just really appreciate you making this for everyone and would love to buy you a cup of coffee!

I’m playing this with a large group of friends on Wednesday and am so excited.

**Comment by ShrimpCryptid** [comment]
Aww, thank you!

The original Secret Hitler board game is shared through the[ Creative Commons BY-NA-SA 4.0 License](https://creativecommons.org/licenses/by-nc-sa/4.0/), which stipulates that the game can only be used for non-commercial purposes. I've previously talked to the team of Secret Hitler and, at the time, they requested that I not include any kind of donation or contribution link on the project.

Out of respect for their wishes, I don't have any setup for donations, though I really appreciate the sentiment! It means so much to me to see people playing and enjoying this project.
