### ISSUE TITLE
Call Special Election

### ISSUE THREAD

**Issue by allredhayden** [ShrimpCryptid/Secret-Hitler-Online#21]
Hi there! We played with a large group tonight and it worked so incredibly well. That was so much fun! We noticed a small thing with the Call Special Election presidential power. The current president was able to choose themselves as the president, but in the rules it says that the president chooses any _other_ player, specifically. Here's the official rule.

> _Call Special Election_
The President chooses any other
player at the table to be the next
Presidential Candidate by passing
that player the President placard.
Any player can become President—even
players that are term-limited. The
new President nominates an eligible
player as Chancellor Candidate and
the Election proceeds as usual.

Seriously thank you SO MUCH for creating such a polished version of the game online. Everyone was so surprised and impressed by the quality.

**Comment by ShrimpCryptid** [comment]
Sorry for the late response on this one! Good catch and thank you for letting me know! The change has been made but needs to be tested, and I'll update this thread once it's live.

**Comment by ShrimpCryptid** [comment]
Fixed as of most recent commit!
