### ISSUE TITLE
Game crashes on custom president

### ISSUE THREAD

**Issue by ErdemGKSL** [ShrimpCryptid/Secret-Hitler-Online#27]
After custom president tour, if the next president is just executed, dead player becomes president but he cant play the game and game stucks on the same screen.

**Comment by ShrimpCryptid** [comment]
Thanks for submitting an issue ticket!

Fairly certain I know what's causing this bug-- the game already checks if the next president is dead and advances past them, but this is likely failing if the next president was the last player in the turn order as the code doesn't loop back to the beginning.

I'll push an update once I get a chance to test this.

**Comment by ShrimpCryptid** [comment]
Tested and confirmed! A new server build is live and fixes this bug.
