### ISSUE TITLE
Heroku Free Tier Expiring

### ISSUE THREAD

**Issue by ShrimpCryptid** [ShrimpCryptid/Secret-Hitler-Online#37]
Hi, everyone!

Heroku's free tier is expiring on November 28th, which means that Secret Hitler Online's backend will need a new host.

I'll be working to port the backend to another service (currently looking into Fly.io!) but it involves quite a bit of work. I hope that I can keep the project running, but I can't make any guarantees yet.

Fingers crossed!

**Comment by ShrimpCryptid** [comment]
Update: I have gotten the fly.io backend working, so as soon as there's a lapse in open games I'll go ahead and make the switch. Fingers crossed that everything works smoothly!

**Comment by allredhayden** [comment]
Yay! Thank you so much for your work. We are all so appreciative!

**Comment by ShrimpCryptid** [comment]
Okay, looks like everything is working correctly. I was able to play through a full game against myself without any issues!
