### ISSUE TITLE
Player list has too much information

### ISSUE THREAD

**Issue by RobertsJim** [ShrimpCryptid/Secret-Hitler-Online#7]
Actual behavior: Websocket sends all players the roles of every player
Expected behavior: Websocket sends `liberals` and `hitler` roles only their own role by default, with some provision for in game events that might reveal more information where an investigating player can see the role of the investigated player (but only the investigating player is sent this info)

**Comment by ShrimpCryptid** [comment]
Hey, thanks for playing and for leaving feedback!
This is something I can start working on-- it would require some additional logic on both the server and web interface. Out of curiosity, was this a big issue for you or other players?

**Comment by RobertsJim** [comment]
I'd say that it's probably not an issue for most people, or if you trust the other players at least.
Certainly not game breaking or anything.

**Comment by ShrimpCryptid** [comment]
Oops, good catch, it's the latter! I made a mistake marking this as complete while it was still on a dev branch.

I'll take a look later today and update the main deployment. @Coniface thank you for the comment!
