### ISSUE TITLE
screen gets stuck on black and needs to be refreshed to fix multiple times in a row

### ISSUE THREAD

**Issue by jeraflare** [ShrimpCryptid/Secret-Hitler-Online#79]
https://imgur.com/a/JIsEDUt

im using firefox btw

**Comment by ShrimpCryptid** [comment]
Huh, that's concerning. Could you provide a bit more detail about what stage of the game this is happening? Are there any other conditions that seem to trigger it?

**Comment by ShrimpCryptid** [comment]
Just following up on this to see if you were able to provide any more detail?

**Comment by ShrimpCryptid** [comment]
Going to close this since there hasn't been any activity on it. Let me know if you encounter this again!
