### ISSUE TITLE
kicking after one hour

### ISSUE THREAD

**Issue by JulianLindner** [ShrimpCryptid/Secret-Hitler-Online#8]
We have had several games with hour where we've got kicked out of the session after one hour.
That's annoying. Maybe is it a better idea to only kick sessions if they really are afk.

**Comment by ShrimpCryptid** [comment]
Were you actively playing in the lobby, or was it one hour after the lobby was created?

**Comment by JulianLindner** [comment]
We were actively playing in the lobby but got kicked after pretty exactly one hour

**Comment by ShrimpCryptid** [comment]
That's interesting... Usually, lobbies are only kicked after 30 minutes of inactivity, so it's possible that your lobby encountered an error state which caused everyone to get kicked.

I'm going to do some digging through the server log. Can you tell me what approximate **day/time (+ time zone)** you were playing during, as well as what your **username** at the time was?

**Comment by JulianLindner** [comment]
was on 3rd of december, Central European Time around 10 - 12 pm.
possible Names:
Juliberaaaal
Juliberal
Juliaaaaaaan

**Comment by ShrimpCryptid** [comment]
I ran a test for 1 hour in a lobby and this issue didn't occur, and I haven't find anything in the log files? Has this happened again since you first reported the issue?

**Comment by ShrimpCryptid** [comment]
Closing for now as I've been unable to replicate this issue.
