### ISSUE TITLE
President Peek shows wrong loyalty

### ISSUE THREAD

**Issue by Gobbie403** [ShrimpCryptid/Secret-Hitler-Online#84]
When the president gets the ability to peek at the loyalty of a player, in three seperate events, all liberal players have shown the fascist loyalty. I currently don't know, if the fascist are shown their correct loyalty.

**Comment by ShrimpCryptid** [comment]
Uhhhh that's bad!! I have a theory about what's causing it, I'll take a look. Thanks for the report!

**Comment by ShrimpCryptid** [comment]
A fixed build is now live and I've tested to make sure that everything is working correctly. Thank you again for the bug report, @Gobbie403!
