### ISSUE TITLE
"Winning" title missing

### ISSUE THREAD

**Issue by JulianLindner** [ShrimpCryptid/Secret-Hitler-Online#9]
We've had to rounds in a row were the game ended after Hitler got choosen as chancelor.
There have not been a "winning"-screen, but the game ended immediately

**Comment by ShrimpCryptid** [comment]
I'll look into this and see if I can recreate it. Do you remember how many players were in your lobby?

**Comment by JulianLindner** [comment]
It was with with 10 players

**Comment by JulianLindner** [comment]
Today with 6 Players: Dec 8, CET 9pm 
Lobby: vggb Playername: Celina

**Comment by ShrimpCryptid** [comment]
Looked through the log files for this one, and it doesn't seem like there was an error on the server. Most likely, the client is reconnecting to the server as the victory happens, which causes the animations to reset and forces the sudden jump to the lobby.

I will report back when I have the time to test this myself! Thanks for reporting this in detail.

**Comment by ShrimpCryptid** [comment]
A hotfix was pushed a few days ago which fixes the bug! Thank you for your patience!
